.TH CHARCOUNT 1 "11 November 20"
.SH NAME
charcount \- count characters in input
.SH SYNOPSIS
\fBcharcount
.SH DESCRIPTION
.I charcount 
counts the characters 
in its input 
and writes the total 
as a single line of text to the output.
.SH EXAMPLES
Count file1's character:
.EX
charcount < file1
.EE
.PP

