.TH CONCAT 1 " 29 November 20"
.SH NAME
concat \- concatenate files
.SH SYNOPSIS
\fBconcat\fR [\fIfile\fR ...]
.SH DESCRIPTION
.I concat 
writes the contents
of each of its file arguments
to its output.
Thus concatenating them into one larger file.
Since concat performs no reformating or interpretation
of the input files, 
it is useful for displaying the contents of a file.

