.TH DETAB 1 "11 November 20"
.SH NAME
detab \- convert tabs to blanks
.SH SYNOPSIS
\fBdetab
.SH DESCRIPTION
\fBdetab\fP copies its input to its output,
expanding horizontal tabs 
to blanks along the way,
so that the output is visually the same as the input,
but contains no tab characters.

Tab stops are assumed to be every four columns.


