.TH ECHO 1 "12 November 20"
.SH NAME
echo \- echo arguments to output
.SH SYNOPSIS
\fBecho\fP  [OPTION]... [STRING]...
.SH DESCRIPTION
.I echo 
copies its command line arguments 
to its output 
as a line of text 
with one space between echo argument.
If there are no arguments, 
no output is produced.

