.TH PRINT 1 " 30 November 20"
.SH NAME
print \- print files with headings 
.SH SYNOPSIS
\fBprint\fR [\fIfile\fR ...]
.SH DESCRIPTION
.I print 
copies each of its argument files in turn
to its output,
inserting page headers and footers and
filling the last page of each file to full length.
A header consists of two blank lines,
a line giving the filename and page number,
and two more blank lines;
a footer consists of two blank lines.
Pages for each file
are numbered starting at one.
If no arguments are specified,
.I print 
prints its standard input;
the file name is null.
.PP
The text of each file is unmodified
-- no attempt is made to fold long lines 
or expand tabs to spaces.


