.TH WORDCOUNT 1 "11 November 20"
.SH NAME
wordcount \- count words in input
.SH SYNOPSIS
\fBwordcount
.SH DESCRIPTION
.I wordcount 
counts the words in its input 
and writes the total 
as a line of text 
to the output.
.PP
A "word" is a maximal sequence 
of characters not containing 
a blank or tab or newline.

